### ISSUE TITLE
Any plans to support wind speed?

### ISSUE THREAD

**Issue by A-Swafford** [swoboda1337/acurite-esphome#7]
I love the ease of use and would be happy to do some testing for you.

I have an atlas 7-in-1 with lightning detection and a windspeed thingy.   

Let me know if windspeed is supported or if there's something I can provide to get it into the code. I'm a big fan of esphome and the ease of the lilygo module makes this better than the spotty mqtt auto-discovery I had set up last time.

**Comment by swoboda1337** [comment]
I actually just added atlas support this week. It should be ready to go. I don't actually have an atlas so I test it by sending data from another esp device. It should work. Let me know if you have issues.

**Comment by swoboda1337** [comment]
I havent added windspeed to the readme yet but its there. I should add that. These are the newer sensors not listed in the readme (sensor.py lists them as well):

      - device: 0x0083
        speed:
          name: "Wind speed"
        direction:  
          name: "Wind direction"
        uv:
          name: "UV index"
        lux:
          name: "Lux value"

**Comment by A-Swafford** [comment]
Excellent. I will purchase the hardware and report back once I have it set up.

**Comment by swoboda1337** [comment]
You get around to trying this yet?
